apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-label
  template:
    metadata:
      labels:
        app: my-nginx-label
    spec:
      containers:
      - name: my-nginx-app
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx-label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
