apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-api-deployment
  labels:
    app: netcore-api
spec:
  selector:
    matchLabels:
      app: netcore-api
  template:
    metadata:
      labels:
        app: netcore-api
    spec:
      containers:
      - name: netcore-api
        image: taugem/netcoreapi:v0.1    
  
---

apiVersion: v1
kind: Service
metadata:
  name: netcore-api-service
  labels:
    app: netcore-api
spec:
  type: ClusterIP
  selector:
    app: netcore-api
  ports:
  - name: http
    port: 5041