apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  labels:
    app: "{{ .Values.deployment.label }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.deployment.label }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.label }}"
    spec:
      containers:
      - name: "{{ .Values.deployment.label }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "{{ .Values.deployment.resources.requests.cpu }}"
            cpu: "{{ .Values.deployment.resources.requests.memory }}"
          limits:
            memory: "{{ .Values.deployment.resources.limits.cpu }}"
            cpu: "{{ .Values.deployment.resources.limits.memory }}"   