apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-api-deployment
  labels:
    app: netcore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netcore-api
  template:
    metadata:
      labels:
        app: netcore-api
    spec:
      containers:
      - name: netcore-api
        image: netcoreapi:0.1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32M"
            cpu: "250m"
          limits:
            memory: "56M"
            cpu: "500m"          
